name: 'Platformsh Backup S3 Action'
description: 'Creates Backups on S3 from Platform.sh projects'
inputs:
  platformsh_project:
    description: 'Platform.sh project ID.'
    required: true
  platformsh_environment:
    description: 'Platform.sh environment name.'
    required: true
  aws_s3_bucket:
    description: 'AWS S3 bucket name.'
    required: true
  with_private_files:
    description: 'whether to backup private files or not'
    required: true
    default: 'no'
  public_files_path:
    description: 'Public File Path'
    required: false
    default: 'web/sites/default/files'
  private_files_path:
    description: 'Private File Path'
    required: false
    default: 'private'

runs:
  using: 'docker'
  image: 'Dockerfile'
